name: tmdb_prj
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  get_it: ^7.2.0
  dio: ^4.0.6
  either_dart: ^0.2.0
  easy_debounce: ^2.0.2+1
  shared_preferences: ^2.0.15
  cached_network_image: ^3.2.3
  fan_carousel_image_slider: ^0.0.1

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.2.1
  mockito: ^5.3.1
  bloc_test: ^9.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

